auto: true

#markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: erikge.com
url: http://erikge.com
feed: /web/article_outline/atom.xml
author_info: <a href="http://erikge.com/">erik ge</a>


exclude: doc_,

＃port: 80
