title: erikge.com
url: http://erikge.com
feed: /assets/atom.xml
author_info: <a href="http://erikge.com/">erik ge</a>
description: the road erikge travalled
disqus_shortname: erikge

owner:
  name: erikge
  email: erikge@qq.com


#markdown: rdiscount
markdown: redcarpet
redcarpet:
  extensions:
    - smart
permalink: articles/:title
pygments: true

paginate_path: "page/:num"
paginate: 10


exclude: [doc_,]

＃port: 80
